name: CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Lint
        uses: docker://oskarstark/php-cs-fixer-ga:3.4.0
        with:
          args: --format=txt --diff --dry-run --using-cache=no --verbose
